services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    depends_on:
      - minio
    ports:
      - "5000:5000"
    environment:

      MLFLOW_S3_PORT: ${MLFLOW_S3_PORT}
      MLFLOW_S3_ENDPOINT_URL: "http://minio:${MLFLOW_S3_PORT}"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - backend

  api:
    build: ./src/api
    container_name: api_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - backend
      - front-api

  frontend:
    build: ./app_front
    container_name: streamlit_front
    volumes:
      - ./app_front:/app
    environment:
      API_URL: http://api_backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - front-api

networks:
  backend:
  front-api:

volumes:
  minio_data:
