services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow_server
    depends_on: [minio]
    ports: ["5000:5000"]
    environment:
      - MLFLOW_S3_ENDPOINT_PORT=${MLFLOW_S3_ENDPOINT_PORT}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:${MLFLOW_S3_ENDPOINT_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Interface Web (Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data  # dossier /data de MinIO 

volumes:
  minio_data:  