version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    # working_dir: /app
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root s3://mlflow/
      --host 0.0.0.0
      --allowed-hosts "mlflow:*, localhost:*, minio:*"
    ports:
      - "5000:5000"
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - minio
    volumes:
      - mlflow_model:/mlflow

  api:
    build:
      context: .
      dockerfile: ./src/api/Dockerfile
    container_name: fastapi_api
    ports:
      - "9090:9090"
    environment:
      FASTAPI_PORT: 9090
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - minio
      - mlflow

  frontend:
    build:
      context: .
      dockerfile: ./src/front/Dockerfile
    container_name: streamlit_front
    ports:
      - "8501:8501"
    environment:
      API_URL: http://api:9090
      MLFLOW_TRACKING_URI: http://mlflow:5000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      - api

volumes:
  minio_data:
  mlflow_model: