name: CI Quality & Security

on:
  push:
    branches: [ main, dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-and-lint:
    name: Quality and Tests
    needs: security-scan
    runs-on: ubuntu-latest
    
    services:
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        # Cette fois, on définit explicitement le point d'entrée pour éviter que le conteneur s'arrête
        options: >-
          --entrypoint /usr/bin/minio
          server /data

  documentation-check:
    name: Documentation Build
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build HTML Documentation
        run: |
          mkdir -p build/html
          uv run sphinx-build -b html docs/source/ build/html