name: CI Quality & Security

on:
  push:
    branches: [ main, dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # test-and-lint:
  #   name: Train & Front Tests
  #   needs: security-scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install uv
  #       run: |
  #         curl -LsSf https://astral.sh/uv/install.sh | sh
  #         echo "$HOME/.local/bin" >> $GITHUB_PATH

  #     - name: Set up Python
  #       run: |
  #         export PATH="$HOME/.local/bin:$PATH"
  #         uv python install 3.12

  #     - name: Run tests
  #       env:
  #         TESTING: "True"
  #         PYTHONPATH: "."
  #         # ON FORCE TOUT EN LOCAL SANS S3
  #         MLFLOW_TRACKING_URI: "sqlite:///mlflow_ci.db"
  #         # On peut mettre une valeur bidon pour S3 car on ne l'utilisera pas
  #         MLFLOW_S3_ENDPOINT_URL: "http://localhost:9000" 
  #         AWS_ACCESS_KEY_ID: "fake"
  #         AWS_SECRET_ACCESS_KEY: "fake"
  #       run: |
  #         # On lance pytest uniquement sur les dossiers train et front
  #         # On exclut les tests qui touchent à l'API/MinIO si besoin
  #         uv run pytest tests/

  documentation-check:
    name: Documentation Build
    # needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Build HTML Documentation
        run: |
          mkdir -p build/html
          uv run sphinx-build -b html docs/source/ build/html