name: CI Quality & Security

on:
  push:
    branches: [ main, dev, master ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-and-lint:
    name: Quality and Tests
    needs: security-scan
    runs-on: ubuntu-latest
    
    services:
      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        # Cette fois, on définit explicitement le point d'entrée pour éviter que le conteneur s'arrête
        options: >-
          --entrypoint /usr/bin/minio
          server /data

    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        
      - name: Set up Python
        run: uv python install 3.12

      - name: Run tests
        env:
          TESTING: "True"
          PYTHONPATH: "."
          MLFLOW_S3_ENDPOINT_URL: "http://127.0.0.1:9000"
          AWS_ACCESS_KEY_ID: "minioadmin"
          AWS_SECRET_ACCESS_KEY: "minioadmin"
          MLFLOW_TRACKING_URI: "sqlite:///mlflow_test.db"
        run: |
          echo "Waiting for MinIO service..."
          # On attend que le port 9000 réponde
          timeout 30s sh -c 'until curl -s http://127.0.0.1:9000/minio/health/live; do sleep 2; done'
          uv run pytest --cov=fastapi_api --cov=app_front .

  documentation-check:
    name: Documentation Build
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build HTML Documentation
        run: |
          mkdir -p build/html
          uv run sphinx-build -b html docs/source/ build/html